name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t yannainghtwe/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true yannainghtwe/react-test npm test

      - run: docker build -t yannainghtwe/multi-client ./client
      - run: docker build -t yannainghtwe/multi-nginx ./nginx
      - run: docker build -t yannainghtwe/multi-server ./server
      - run: docker build -t yannainghtwe/multi-worker ./worker

      - run: docker push yannainghtwe/multi-client
      - run: docker push yannainghtwe/multi-nginx
      - run: docker push yannainghtwe/multi-server
      - run: docker push yannainghtwe/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          wait_for_deployment: false
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-831324844334
          region: us-east-1
          version_label: ${{ github.run_id }}
          deployment_package: deploy.zip